branch-defaults:
  master:
    environment: devenv
    group_suffix: null
global:
  application_name: test
  default_ec2_keyname: null
  default_platform: PHP 7.0
  default_region: us-west-2
  profile: eb-cli
  sc: git
